#!/usr/bin/python

import sys

edge = {}

for line in sys.stdin:
  line = line.strip()
  if len(line)==0: continue
  if line[0] == '#': continue
  if line[0] != 'e': continue

  tok = line.split(" ")
  u = int(tok[1])
  v = int(tok[2])

  key = str(u) + ":" + str(v)

  edge[key] = 1

print "graph {"
for key in edge:
  tok = key.split(":")
  print "  " + tok[0] + " -- " + tok[1] + ";"

print "}"
