#!/usr/bin/python

import sys

line_no = 0

edge = {}

comment = []
out_edge = []

max_edge = 1

for line in sys.stdin:
  line = line.strip()
  line_no+=1

  if len(line) == 0: continue
  if line[0] == 'c':
    comment.append(line)
    continue

  if line[0] != 'e':
    #print line
    continue

  tok = line.split(' ')
  if len(tok) != 3:
    print "ERROR: invalid line", line_no, ":", line
    sys.exit(-1)

  u = int(tok[1])
  v = int(tok[2])

  if u>v:
    u,v = v,u

  max_edge = max(u, v, max_edge)

  key = str(u) + ":" + str(v)

  if key in edge:
    continue

  out_edge.append( "e " +  str(u) + " " + str(v)  )

  edge[key] = 1;

for v in comment:
  print v

print "p edge", max_edge, len(out_edge)

for e in out_edge:
  print e
